#!/bin/sh
touch 'sleeping: $1' >> /tmp/sleep
case $1 in
 pre)
  /sbin/ifdown eth0
  /sbin/ifdown wlan0
  /sbin/ifdown wlan1
  /usr/bin/pkill openvpn
  /usr/bin/pkill dhcpd
  /usr/bin/pkill wpa_supplicant
  ;;
esac
